name: Data Pipeline

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set custom DVC cache directory
        run: |
          mkdir -p .dvc_cache
          dvc config cache.dir .dvc_cache
          dvc config --list


  fetch_weather_data:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure DVC
        run: |
          dvc remote add -f origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/lanaben/news-prediction-app.s3
          dvc remote modify origin --local access_key_id ${{ secrets.ACCES_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data with DVC
        env:
          DVC_CACHE_DIR: /home/runner/work/news-prediction-app/news-prediction-app/.dvc_cache
        run: dvc pull

      - name: Add and commit data to DVC
        run: |
          git config --global user.name 'lanaben'
          git config --global user.email 'lanaben@users.noreply.github.com'
          git fetch origin main
          git pull --rebase origin main
          python src/data/fetch_news_data.py
          dvc add data/raw/articles.csv
          git add data.dvc
          dvc status
          dvc push
          git commit -m "Fetch news data."
          git push https://lanaben:${{ secrets.IIS }}@github.com/lanaben/news-prediction-app.git main
        env:
          IIS: ${{ secrets.IIS }}